/*
 *  This sql script insert data into Part table.
 *  Data are randomly generated by private java program.
 *
 *  Author: Yuanjun Ma
 */


INSERT INTO Part VALUES ('PRT0001', 'Engine', 30000);
INSERT INTO Part VALUES ('PRT0002', 'Hull', 30000);
INSERT INTO Part VALUES ('PRT0003', 'Wing', 20000);
INSERT INTO Part VALUES ('PRT0004', 'Lightyear Navigation', 5000);
INSERT INTO Part VALUES ('PRT0005', 'G-Force Tractor Bean', 35000);
INSERT INTO Part VALUES ('PRT0006', 'Energy conservation Boost', 12000);
INSERT INTO Part VALUES ('PRT0007', 'Skyline Cargo Box', 8000);
INSERT INTO Part VALUES ('PRT0008', 'SXoThermal Shield', 25000);
INSERT INTO Part VALUES ('PRT0009', 'Galaxy Bio Sensor', 18000);
INSERT INTO Part VALUES ('PRT0010', 'Hallow Deck', 25000);
INSERT INTO Part VALUES ('PRT0011', 'Manual Operation Cockpit', 8000);
INSERT INTO Part VALUES ('PRT0012', 'Classic Operation Cockpit', 8000);
INSERT INTO Part VALUES ('PRT0013', 'Seethrough Flooring', 10000);
INSERT INTO Part VALUES ('PRT0014', 'Sick Bay', 45000);
INSERT INTO Part VALUES ('PRT0015', 'Cargo Bay', 35000);
INSERT INTO Part VALUES ('PRT0016', 'Reconnaissance Satellite', 45000);
INSERT INTO Part VALUES ('PRT0017', 'Search and Rescue Satellite', 45000);
INSERT INTO Part VALUES ('PRT0018', 'Atomic Teleportation Room', 35000);
INSERT INTO Part VALUES ('PRT0019', 'Designer''s Bridge', 60000);
